services:
  crawler:
    build:
      context: ../../
      dockerfile: docker/crawler/Dockerfile.local
    volumes:
      - ../../src:/app/src
      - ../../data:/app/data
      - ../../targets.txt:/app/targets.txt
    env_file:
      - ../../.env
